"""Initial

Revision ID: f1f07453d137
Revises: 
Create Date: 2017-10-30 21:12:05.066882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f07453d137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job_order', sa.Integer(), nullable=True),
    sa.Column('remote_path', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=True),
    sa.Column('transferred', sa.Float(), nullable=True),
    sa.Column('fs_type', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('log', sa.String(), nullable=True),
    sa.Column('worker', sa.Boolean(), nullable=True),
    sa.Column('datetime_added', sa.DateTime(), nullable=True),
    sa.Column('datetime_downloaded', sa.DateTime(), nullable=True),
    sa.Column('datetime_completed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
